### ISSUE TITLE
Some apps working intermittently

### ISSUE THREAD

**Issue by saksham12** [cryspuwaterloo/privacyguard#23]
When the VPN is turned on, some of the apps stop working. For example, Starbucks app does not find nearby stores. The Amazon app does not work at all.

Device: Nexus 6p running Android 7

**Comment by uhengart** [comment]
Thanks for your feedback. I can observe the problem for the Amazon Shopping app, but not for Starbucks. Can you give me a sequence of steps that lead to a failure? Thanks.

**Comment by saksham12** [comment]
Nothing fancy in the sequence of steps. I just connected the VPN, opened the starbucks app. Went to orders (however the nearby stores don't show up). When I click on View Map, the map doesn't load. The device isn't rooted and has stock Android. In addition, while using other apps, PrivacyGuard crashed a couple times due to OutOfMemoryException. I have attached the logs for the same.
[crash_log.txt](https://github.com/cryspuwaterloo/privacyguard/files/1106513/crash_log.txt)

**Comment by uhengart** [comment]
The Amazon app should work now. I've hardcoded a rule not to intercept its TLS traffic. At some point we need to add a feature that lets the user disable TLS interception on a per app basis.

I still can't reproduce the Starbucks failure. Can you make sure that you use the most recent version of PrivacyGuard and then post a log?

We need to do some serious cleanup in terms of logging, which we'll hopefully make the out of memory issues go way.

Thanks.

**Comment by saksham12** [comment]
Ok, I was doing something wrong with the starbucks app. It is working now, after a clean install. Could you please elaborate a bit on why PrivacyGuard wasn't able to run Amazon?

**Comment by uhengart** [comment]
Amazon supports certificate pinning so it expects the server to have a particular certificate. Most apps with certificate pinning implement the certificate checking while setting up the TLS connection. For these apps, setting up the TLS connection will fail when PrivacyGuard intercepts TLS traffic and sends a fake certificate to the app.  PrivacyGuard remembers this failure and won't intercept TLS for this site when another connection to the site is opened.

The Amazon app implements certificate pinning at the app level. So setting up the TLS connection will not fail and PrivacyGuard will not detect a problem. Once the TLS connection is set up, the Amazon app checks the fake certificate received from PrivacyGuard and terminates the connection. However, PrivacyGuard can't distinguish this kind of termination from regular connection shutdowns. Since PrivacyGuard did not detect a failure, it will also try to intercept all following TLS connection attempts to the same site and all attempts will be terminated right away by the app.

**Comment by saksham12** [comment]
Thanks for the detailed explanation!
